---
- hosts: test
  sudo: yes
  tasks:
    - name: Check if httpd is installed
      yum: 
        name: httpd
        update_cache: yes
        state: latest

    - name: Create page with "Hello, world!"
      template: src=index.html dest=/var/www/html/index.html backup=yes

    - name: Check if httpd is running
      service: name=httpd state=started